
image:
  repository: httpd
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
     kubernetes.io/ingress.class: nginx
     ingress.kubernetes.io/auth-secret: web-sofixit-secret
     ingress.kubernetes.io/auth-type: basic
     ingress.kubernetes.io/auth-realm: 'Authentication required'
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: web-sofixit.local
  tls:
    - secretName: web-sofixit-tls
      hosts:
        - web-sofixit.local

persistence:
  enabled: true
  storageClass: nfs-client
  accessMode: ReadWriteOnce
  size: 1Gi

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi


