apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-sofixit.fullname" . }}
spec:
  selector:
    app: {{ include "web-sofixit.fullname" . }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
