{{- $svcPort := .Values.service.port -}}
{{- $fullName := include "web-sofixit.fullname" .}}
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "web-sofixit.fullname" . }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  selector:
    matchLabels:
      app: {{ include "web-sofixit.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "web-sofixit.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
  {{- if .Values.ingress.tls }}
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}  
  rules:
  {{- range .Values.ingress.hosts }}
  - host:  {{ .host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: {{ $fullName }}
            port:
              number: {{ $svcPort }}
  {{- end }}
{{- end }}








